python/Django/Login/Login/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls), path("", include("LoginApp.urls"))]

python/Django/Login/LoginApp/urls.py
from django.urls import path
from . import views

app_name = "LoginApp"
urlpatterns = [
    path("", views.homepage, name="hompage"),
    path("register", views.register, name="register"),
    path("login", views.user_login, name="user-login"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("logout", views.user_logout, name="user-logout"),
]

python/Django/Login/LoginApp/models.py
from django.db import models

# Create your models here.

python/Django/Login/LoginApp/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.forms.widgets import PasswordInput, TextInput
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())

python/Django/Login/LoginApp/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from .forms import CreateUserForm, LoginForm

# Authentication models and functions
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def homepage(request):
    return render(request, "LoginApp/index.html")


def register(request):
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("LoginApp:user-login")
        else:
            messages.error(request, "Not valid.")
            print("\nNot valid\n")

    context = {"registerform": form}
    return render(request, "LoginApp/register.html", context=context)


def user_login(request):

    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("LoginApp:dashboard")
    form = LoginForm()
    context = {"loginform": form}
    return render(request, "LoginApp/user-login.html", context)


def user_logout(request):
    logout(request)
    return redirect("LoginApp:user-login")


@login_required(login_url="LoginApp:user-login")
def dashboard(request):
    return render(request, "LoginApp/dashboard.html")

python/Django/Login/LoginApp/templates/LoginApp/dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      href="{% static 'LoginApp/style.css' %}" />
    <title>Dashboard</title>
  </head>
  <body>
    <h1>You've logged in.</h1>
    <a href="{% url 'LoginApp:user-logout' %}">Logout</a>
  </body>
</html>

python/Django/Login/LoginApp/templates/LoginApp/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0" />

    {% load static %}
    <link
      rel="stylesheet"
      href="{% static 'LoginApp/style.css' %}" />
    <title>Hompage</title>
  </head>
  <body>
    <h1>This is Hompage</h1>
  </body>
</html>

python/Django/Login/LoginApp/templates/LoginApp/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      href="{% static 'LoginApp/style.css' %}" />
    <title>Document</title>
  </head>
  <body>
    {% if messages %} {% for message in messages %}
    <div style="background-color: red; color: white">{{ message }}</div>
    {% endfor %} {% endif %}
    <h1>Register Now!</h1>
    <form method="POST">
      {% csrf_token %} {{registerform.as_p}}
      <input
        type="submit"
        value="Register" />
    </form>
  </body>
</html>

python/Django/Login/LoginApp/templates/LoginApp/user-login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      href="{% static 'LoginApp/style.css' %}" />
    <title>Document</title>
  </head>
  <body>
    <h1>Login Now!</h1>
    <form method="POST">
      {% csrf_token %} {{loginform.as_p}}
      <input
        type="submit"
        value="Register" />
    </form>
  </body>
</html>

python/Django/Login/LoginApp/templates/LoginApp/user-logout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Logged out</h1>
  </body>
</html>